server:
  servlet:
    context-path: /games
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT-8&createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/


mybatis:
  configuration:
    log-imp: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full
  type-aliases-package: com.playgame.pojo
  mapper-locations: classpath:mapper/*.xml

